import { useState, useMemo } from 'react'
import Modal from '../masters/Modal'
import { downloadCsv, todayStamp } from '../../utils/csv'

const ELIM_TYPES = {
  RECEIVABLE_PAYABLE: { label: '債権債務消去',   cls: 'elim-badge--rp' },
  REVENUE_EXPENSE:    { label: '売上高・仕入消去', cls: 'elim-badge--re' },
  CUSTOM:             { label: 'その他',           cls: 'elim-badge--custom' },
}

const EMPTY = {
  yearMonth: '',
  type: 'RECEIVABLE_PAYABLE',
  description: '',
  debitSubsidiaryId: '',
  debitAccountCode: '',
  debitAccountName: '',
  creditSubsidiaryId: '',
  creditAccountCode: '',
  creditAccountName: '',
  amountJpy: '',
}

function validate(form) {
  const errs = {}
  if (!form.yearMonth)          errs.yearMonth         = '年月は必須です'
  if (!form.description.trim()) errs.description       = '摘要は必須です'
  if (!form.debitAccountName.trim())  errs.debitAccountName  = '借方科目名は必須です'
  if (!form.creditAccountName.trim()) errs.creditAccountName = '貸方科目名は必須です'
  const amt = Number(String(form.amountJpy).replace(/,/g, ''))
  if (!form.amountJpy || isNaN(amt) || amt <= 0) errs.amountJpy = '金額は正の数で入力してください'
  return errs
}

export default function Eliminations({ eliminations, saveElimination, deleteElimination, subsidiaries }) {
  const [modal,       setModal]       = useState(null)
  const [form,        setForm]        = useState(EMPTY)
  const [errors,      setErrors]      = useState({})
  const [filterMonth, setFilterMonth] = useState('')

  const defaultMonth = new Date().toISOString().slice(0, 7)

  const sorted = useMemo(() =>
    [...eliminations].sort((a, b) =>
      b.yearMonth.localeCompare(a.yearMonth) || a.type.localeCompare(b.type)
    ), [eliminations])

  const displayed = filterMonth ? sorted.filter(e => e.yearMonth === filterMonth) : sorted

  const totalElim = useMemo(() => displayed.reduce((s, e) => s + (e.amountJpy || 0), 0), [displayed])

  const subMap = useMemo(() => Object.fromEntries(subsidiaries.map(s => [s.id, s])), [subsidiaries])
  const subName = id => subMap[id]?.name || id || '（親会社）'

  function openAdd() {
    setForm({ ...EMPTY, yearMonth: filterMonth || defaultMonth })
    setErrors({})
    setModal({ mode: 'add' })
  }
  function openEdit(e) { setForm({ ...e, amountJpy: e.amountJpy.toString() }); setErrors({}); setModal({ mode: 'edit', id: e.id }) }

  function setField(k, v) {
    setForm(f => ({ ...f, [k]: v }))
    setErrors(e => { const n = { ...e }; delete n[k]; return n })
  }

  function handleSave() {
    const errs = validate(form)
    if (Object.keys(errs).length) { setErrors(errs); return }
    const item = {
      ...form,
      amountJpy: Number(String(form.amountJpy).replace(/,/g, '')),
      isAutoGenerated: false,
    }
    if (modal.mode === 'edit') item.id = modal.id
    saveElimination(item)
    setModal(null)
  }

  function handleAutoGenerate() {
    if (!filterMonth) { alert('年月を選択してください'); return }
    // 相殺消去: 子会社間で同額の債権/債務を見つけて自動消去仕訳を生成
    // ここでは簡単なプレースホルダーを生成するデモ
    const id = `ELIM-AUTO-${Date.now()}`
    saveElimination({
      id,
      yearMonth: filterMonth,
      type: 'RECEIVABLE_PAYABLE',
      description: '（自動）内部債権債務消去',
      debitSubsidiaryId:  '',
      debitAccountCode:   '2110',
      debitAccountName:   '買掛金（内部）',
      creditSubsidiaryId: '',
      creditAccountCode:  '1110',
      creditAccountName:  '売掛金（内部）',
      amountJpy: 0,
      isAutoGenerated: true,
    })
    alert('消去仕訳の雛形を作成しました。金額を編集してください。')
  }

  function exportCsv() {
    const header = ['年月', '種別', '摘要', '借方会社', '借方科目', '貸方会社', '貸方科目', '消去額(JPY)']
    const rows = displayed.map(e => [
      e.yearMonth,
      ELIM_TYPES[e.type]?.label || e.type,
      e.description,
      subName(e.debitSubsidiaryId),
      `${e.debitAccountCode} ${e.debitAccountName}`.trim(),
      subName(e.creditSubsidiaryId),
      `${e.creditAccountCode} ${e.creditAccountName}`.trim(),
      e.amountJpy,
    ])
    downloadCsv(`相殺消去_${todayStamp()}.csv`, [header, ...rows])
  }

  const subOptions = [
    { id: '', name: '（親会社）' },
    ...subsidiaries.filter(s => s.isActive !== false),
  ]

  return (
    <div className="je">
      <div className="je__page-header">
        <div className="je__breadcrumb">会計システム › 連結会計 › 相殺消去</div>
        <div className="je__title-row">
          <h1 className="je__title">相殺消去</h1>
          <span className="je__spec-badge">{eliminations.length} 件</span>
        </div>
      </div>

      <div className="jl-toolbar">
        <button className="je-btn je-btn--primary" onClick={openAdd}>＋ 消去仕訳を追加</button>
        <button className="je-btn je-btn--outline" onClick={handleAutoGenerate}>⚡ 自動生成</button>
        <input type="month" className="je-input" style={{ width: 160 }}
          value={filterMonth} onChange={e => setFilterMonth(e.target.value)} />
        {filterMonth && <button className="je-btn je-btn--ghost" onClick={() => setFilterMonth('')}>クリア</button>}
        <button className="je-btn je-btn--outline" style={{ marginLeft: 'auto' }}
          onClick={exportCsv} disabled={displayed.length === 0}>
          📄 CSV出力
        </button>
      </div>

      <section className="je-card">
        <div className="je-card__body je-card__body--flush">
          <div className="je-table-wrap">
            <table className="jl-table">
              <thead>
                <tr>
                  <th className="jl-th">年月</th>
                  <th className="jl-th">種別</th>
                  <th className="jl-th">摘要</th>
                  <th className="jl-th">借方</th>
                  <th className="jl-th">貸方</th>
                  <th className="jl-th jl-th--right">消去額 (JPY)</th>
                  <th className="jl-th jl-th--center">操作</th>
                </tr>
              </thead>
              <tbody>
                {displayed.length === 0 ? (
                  <tr><td colSpan={7} className="jl-empty-cell">消去仕訳がありません</td></tr>
                ) : (
                  displayed.map((e, idx) => (
                    <tr key={e.id} className={`jl-tr ${idx % 2 === 1 ? 'jl-tr--alt' : ''}`}>
                      <td className="jl-td jl-td--date">{e.yearMonth}</td>
                      <td className="jl-td">
                        <span className={`elim-badge ${ELIM_TYPES[e.type]?.cls || ''}`}>
                          {ELIM_TYPES[e.type]?.label || e.type}
                        </span>
                        {e.isAutoGenerated && <span className="elim-auto-badge">自動</span>}
                      </td>
                      <td className="jl-td">{e.description}</td>
                      <td className="jl-td" style={{ fontSize: 12 }}>
                        <div className="elim-entry-side">
                          <span className="elim-company">{subName(e.debitSubsidiaryId)}</span>
                          <span className="ms-code-badge ms-code-badge--sm">{e.debitAccountCode}</span>
                          {e.debitAccountName}
                        </div>
                      </td>
                      <td className="jl-td" style={{ fontSize: 12 }}>
                        <div className="elim-entry-side">
                          <span className="elim-company">{subName(e.creditSubsidiaryId)}</span>
                          <span className="ms-code-badge ms-code-badge--sm">{e.creditAccountCode}</span>
                          {e.creditAccountName}
                        </div>
                      </td>
                      <td className="jl-td jl-td--amount">¥{e.amountJpy.toLocaleString('ja-JP')}</td>
                      <td className="jl-td jl-td--actions">
                        <button className="jl-btn jl-btn--edit"   onClick={() => openEdit(e)}>編集</button>
                        <button className="jl-btn jl-btn--delete" onClick={() => { if (window.confirm('削除しますか？')) deleteElimination(e.id) }}>削除</button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
              {displayed.length > 0 && (
                <tfoot>
                  <tr className="jl-tr--total">
                    <td colSpan={5} className="jl-td" style={{ fontWeight: 700 }}>消去合計</td>
                    <td className="jl-td jl-td--amount" style={{ fontWeight: 700 }}>¥{totalElim.toLocaleString('ja-JP')}</td>
                    <td></td>
                  </tr>
                </tfoot>
              )}
            </table>
          </div>
        </div>
      </section>

      {modal && (
        <Modal title={modal.mode === 'add' ? '消去仕訳を追加' : '消去仕訳を編集'}
          onClose={() => setModal(null)} size="lg">
          <div className="ms-form">
            <div className="ms-form-row ms-form-row--2">
              <div className="je-field">
                <label className="je-label je-label--required">年月</label>
                <input type="month" className={`je-input ${errors.yearMonth ? 'je-input--error' : ''}`}
                  value={form.yearMonth} onChange={e => setField('yearMonth', e.target.value)} />
                {errors.yearMonth && <span className="je-field-error">{errors.yearMonth}</span>}
              </div>
              <div className="je-field">
                <label className="je-label je-label--required">種別</label>
                <select className="je-select" value={form.type} onChange={e => setField('type', e.target.value)}>
                  {Object.entries(ELIM_TYPES).map(([k, v]) => (
                    <option key={k} value={k}>{v.label}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="je-field">
              <label className="je-label je-label--required">摘要</label>
              <input className={`je-input ${errors.description ? 'je-input--error' : ''}`}
                value={form.description} onChange={e => setField('description', e.target.value)}
                placeholder="子会社A 売上高・仕入高の相殺" maxLength={80} />
              {errors.description && <span className="je-field-error">{errors.description}</span>}
            </div>

            <div className="elim-dr-cr-grid">
              <div>
                <div className="elim-side-title">借方</div>
                <div className="je-field">
                  <label className="je-label">会社</label>
                  <select className="je-select" value={form.debitSubsidiaryId}
                    onChange={e => setField('debitSubsidiaryId', e.target.value)}>
                    {subOptions.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                </div>
                <div className="ms-form-row ms-form-row--2">
                  <div className="je-field">
                    <label className="je-label">科目コード</label>
                    <input className="je-input" value={form.debitAccountCode}
                      onChange={e => setField('debitAccountCode', e.target.value)} maxLength={10} />
                  </div>
                  <div className="je-field">
                    <label className="je-label je-label--required">科目名</label>
                    <input className={`je-input ${errors.debitAccountName ? 'je-input--error' : ''}`}
                      value={form.debitAccountName}
                      onChange={e => setField('debitAccountName', e.target.value)} maxLength={40}
                      placeholder="買掛金" />
                    {errors.debitAccountName && <span className="je-field-error">{errors.debitAccountName}</span>}
                  </div>
                </div>
              </div>
              <div>
                <div className="elim-side-title">貸方</div>
                <div className="je-field">
                  <label className="je-label">会社</label>
                  <select className="je-select" value={form.creditSubsidiaryId}
                    onChange={e => setField('creditSubsidiaryId', e.target.value)}>
                    {subOptions.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                </div>
                <div className="ms-form-row ms-form-row--2">
                  <div className="je-field">
                    <label className="je-label">科目コード</label>
                    <input className="je-input" value={form.creditAccountCode}
                      onChange={e => setField('creditAccountCode', e.target.value)} maxLength={10} />
                  </div>
                  <div className="je-field">
                    <label className="je-label je-label--required">科目名</label>
                    <input className={`je-input ${errors.creditAccountName ? 'je-input--error' : ''}`}
                      value={form.creditAccountName}
                      onChange={e => setField('creditAccountName', e.target.value)} maxLength={40}
                      placeholder="売掛金" />
                    {errors.creditAccountName && <span className="je-field-error">{errors.creditAccountName}</span>}
                  </div>
                </div>
              </div>
            </div>

            <div className="je-field">
              <label className="je-label je-label--required">消去額 (JPY)</label>
              <input className={`je-input ${errors.amountJpy ? 'je-input--error' : ''}`}
                value={form.amountJpy} onChange={e => setField('amountJpy', e.target.value)}
                placeholder="1000000" style={{ maxWidth: 200 }} />
              {errors.amountJpy && <span className="je-field-error">{errors.amountJpy}</span>}
            </div>

            <div className="ms-modal-actions">
              <button className="je-btn je-btn--secondary" onClick={() => setModal(null)}>キャンセル</button>
              <button className="je-btn je-btn--primary" onClick={handleSave}>保存</button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  )
}
